function [] = edgeNumChange_draw(changeEdgeNumResult)
    global figure_Num;
    figure_Num = figure_Num + 1;
    figure(figure_Num);
    avrTime_Real_myOffload = round([changeEdgeNumResult.avrTime.myOffload].*1000);
    avrTime_Real_mmssOffload = round([changeEdgeNumResult.avrTime.mmssOffload].*1000);
    avrTime_Real_randomOffload = round([changeEdgeNumResult.avrTime.randomOffload].*1000);
    avrTime_Real_allInDeviceOffload = round([changeEdgeNumResult.avrTime.allInDeviceOffload].*1000);
%     avrTime_Real_allInEdgeOffload = round([changeEdgeNumResult.avrTime.allInEdgeOffload].*1000);
%     avrTime_Real_allInCloudOffload = round([changeEdgeNumResult.avrTime.allInCloudOffload].*1000);
    Xlength = length(avrTime_Real_myOffload);
    Ylength = max([
        avrTime_Real_myOffload,...
        avrTime_Real_mmssOffload,...
        avrTime_Real_randomOffload,...
        avrTime_Real_allInDeviceOffload...
...%         avrTime_Real_allInEdgeOffload,...
...%         avrTime_Real_allInCloudOffload...
    ]);
    avrTime_Real_X = 1:1:Xlength*1;
    plot(...
    avrTime_Real_X,avrTime_Real_myOffload,'-*r',...
    avrTime_Real_X,avrTime_Real_mmssOffload,'-og',...
    avrTime_Real_X,avrTime_Real_randomOffload,'-xc',...
    avrTime_Real_X,avrTime_Real_allInDeviceOffload, '-db'...
    ); %线性，颜色，标记
    % axis([0,6,0,700])  %确定x轴与y轴框图大小
    set(gca,'XTick',avrTime_Real_X) %x轴范围1-6，间隔1
    set(gca,'YTick',[0:50:(Ylength + 100)]) %y轴范围0-700，间隔100
    legend(...
    '本章卸载策略',...
    '基于损失制排队系统的卸载策略',...
    '随机卸载策略',...
    '不协同策略'...
    );   %右上角标注
    xlabel('边缘服务器个数（个）')  %x轴坐标描述
    ylabel('任务平均完成时延（毫秒）') %y轴坐标描述

    figure_Num = figure_Num + 1;
    figure(figure_Num);
    p_offload_device = round([changeEdgeNumResult.myOffloadSimulationData.pOffDevice], 2);
    plot(...
    avrTime_Real_X,p_offload_device,'-*r'...
    ); %线性，颜色，标记
    axis([1, 10, 0, floor(max(p_offload_device)*10)/10 + 0.1]);
    set(gca,'XTick',avrTime_Real_X)
    set(gca,'YTick',[0:0.1:1]) %y轴范围0-700，间隔100    legend('设备','边缘节点');
    xlabel('边缘服务器个数（个）')  %x轴坐标描述
    ylabel('被卸载任务的比率（×100%）'); %y轴坐标描述    
    
    figure_Num = figure_Num + 1;
    figure(figure_Num);
    p_offload_edge = round([changeEdgeNumResult.myOffloadSimulationData.pOffEdge], 2);
    plot(...
    avrTime_Real_X,p_offload_edge,'-*r'...
    ); %线性，颜色，标记    
    axis([1, 10, 0, floor(max(p_offload_edge)*10)/10 + 0.1]);
    set(gca,'XTick',avrTime_Real_X)
    set(gca,'YTick',[0:0.1:1]) %y轴范围0-700，间隔100    legend('设备','边缘节点');
    xlabel('边缘服务器个数（个）')  %x轴坐标描述
    ylabel('被卸载任务的比率（×100%）'); %y轴坐标描述    
    
end

